### ISSUE TITLE
Decide on a support tool and workflow

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2555]
**Context:** [Continuing our discussion from the process [doc](https://docs.google.com/document/d/1Qru39fK-JiySdorIDMOaI6V2puldABmz9pVeFiHm1rc/edit?usp=sharing)]
Due to Piazza's existing data/advertisement policies and the benefits offered by a new discussion tool named Ed, few courses across the campus are transitioning to Ed. As a result, The campus is considering a long-term subscription for this tool and has a year-long subscription with Ed and Piazza.

However, Only a few courses like CS 61A have made the transition to Ed. Many courses like the intro to public health are still using Piazza (based on my current understanding), resulting in us choosing between the following scenarios,

- Create a centralized Piazza discussion board to cater to the needs of most courses still using Piazza while encouraging the few courses who moved to Ed to use Piazza to raise/track Datahub requests/queries. Make the decision to change to Ed next year when most courses change. 

- Create a centralized discussion board in Ed this year and encourage most courses using Piazza to use Ed to raise/track Datahub issues/queries. 

- Create a centralized discussion board across Piazza and Ed and track all the requests across both the tools _(Not an ideal scenario)_

Additionally, We should encourage the individual courses to have their channel in the tool of their choice and have a hub evangelist answer student queries. If that setup is not feasible, then they can escalate issues to a centralized channel. This way, only TA/GSIs need to go through the complexity of using multiple tools while students can still keep posting problems in the same tool that gets used for their course.

**Decision to be Made**
- Finalize the tool for the support process amongst the two alternatives - Piazza and Ed

**Tasks to be completed:**

- [x] - Finalize the tool
- [x] - Create the required documentation for Tier I FAQ!
- [x] - Create a support channel in the tool
- [x] - Communicate the support process to course admins through slack and email
- [ ] - Update the new process in the home page of Datahub

**Comment by yuvipanda** [comment]
I think our options are to have it where most of our classes are (which might be Piazza) or on both.

**Comment by balajialg** [comment]
Yes, It seems like it is Piazza that will get widely used. I will speak to folks at RTL to get a sense of Ed's reach across other courses.

**Comment by balajialg** [comment]
Folks at RTL shared that there were around 270 instructors who used Ed and 3,548 instructors who used Piazza across the campus last year. I am assuming the majority of the classes will continue to use Piazza as their primary tool for engagement with students. Considering this data, I am proposing the following process,

- We have a general Piazza channel open to all hubs across the campus
- One Ed channel dedicated to Data 8. Can expand to other courses depending on the requests from the course staff!
- Recommend all the groups using Slack to move to Piazza/Ed depending on their course affiliation

**Let me know if this is something that doesn't make sense to you.** 

The only way to make this successful is to recommend users move away from Slack strongly. Otherwise, it will be a costly effort to monitor three different tools regularly. Thoughts?

**Comment by yuvipanda** [comment]
>     * One Ed channel dedicated to Data 8.

Do the data8 staff already run one here? 



> Recommend all the groups using Slack to move to Piazza/Ed depending on their course affiliation

I think it's important to try not change course practices as much as possible. Instead, my suggestion is that we ask them to come to the central piazza as the place for getting in touch with us, and let them manage it internally however they want. While I agree that moving away from slack is helpful, it's also probably a losing battle if folks use slack for everything else in their course. I think we should say that *we* won't monitor their slacks, and will monitor a specific piazza for escalations. This also limits the number of piazza / ed things we have to monitor.

**Comment by balajialg** [comment]
Yes, Data 8 course staff have moved to Ed from Piazza. Re: Conversation thread with Ani! Considering the volume of Data 8, we might need to support their Ed channel (at least that's the expectation I got from the conversation with Ani)

I like your articulation that "We won't monitor their specific slack channel and will monitor a specific piazza for escalations".

**Comment by balajialg** [comment]
What is the effective way to communicate the support process to the teaching staff? How did the outreach happen previously? In the next few days, I would like to send an outreach message to the faculty and teaching staff through the [email list ](https://github.com/berkeley-dsep-infra/datahub/issues/2197) you all had created. I want to get your perspective on whether this is an effective way to do that? Are there other means we should use to ensure that they are bought into this process?

**I am thinking of structuring the message in the following ways**

- Issues that happen to be a blocker: Follow the process, Share it in the centralized Piazza channel. E.g., [404 errors]
- Issues that are not blockers: Can directly raise the issue using the [bug template](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=bug&template=bug_report.yml) available in Github instead of posting it in Piazza. Eg: [This](https://github.com/berkeley-dsep-infra/datahub/issues/2532)

**Comment by yuvipanda** [comment]
@balajialg we can also change the content on the datahub home pages.

**Comment by balajialg** [comment]
@yuvipanda Sounds great! thanks Yuvi

**Comment by yuvipanda** [comment]
@balajialg what needs to be done here?

**Comment by balajialg** [comment]
@yuvipanda Thanks for bringing this thread alive! TL;DR: We need to circulate the FAQ document with the tiered support process and SLA to the teaching team in terms of the next steps. 
However, I have not been actively doing that due to the following reason,

We are using  Data 100 Piazza as a proof of concept to see how easy it is to troubleshoot and resolve immediate issues through the tool. However, I got the feedback from @felder that Piazza sends way too many notifications making it difficult to parse out the signal from the noise (which I strongly agree with). Considering that, I am ambivalent about moving to the Piazza path directly! I am not sure whether it is solving a big problem while creating additional problems to solve.

Given this context and considering that the nonurgent issues are resolved quickly through Github, I assumed that focusing on outage communication-related support processes would yield maximum benefit to the team. What do you think?

**Comment by balajialg** [comment]
**@ryanlovett's suggestion during sprint planning meeting:**  Try using piazza as a nonadmin user! 

**Next Steps from Sprint Planning Meeting:** 
- @balajialg to connect with @felder to get his thoughts on moving the troubleshooting slack communication to this [piazza channel](https://piazza.com/class/ksqmnrrhvcl11f).
- Based on the #2197 thread, exploring the option to create an additional entry for Datahub on the status page of Berkeley IT!

**Comment by balajialg** [comment]
Update on this,

1. Datahub Status was added to the [System Status Dashboard](https://systemstatus.berkeley.edu/)
2. Considering the possibility that Piazza's contract will end this year, @felder suggested rethinking from tools standpoint
3. Exploring the idea of moving files retrieval requests to ticketing system considering FERPA guidelines
