### ISSUE TITLE
Develop Tier I FAQs for GSI/TA's acting as admins for respective hubs

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2570]
**Summary:**
Through user research with 5 GSI/TAs, I learned that they usually reach out to their peers/use their intuition/reach out to the datahub support slack group to raise their issues. They don't refer to any specific resource whenever a student raises an issue. This leads to a hypothesis that **"If we provide supportive documentation then GSI/TAs could solve for some of the raised issues at their end"**
 
Considering the improved support process outlined, it will be essential in empowering GSI/TA's by providing them with relevant information. to solve issues that they could potentially solve at their end

**User Story**
As a GSI/TA for a hub, I have a support resource that highlights the most commonly occurred errors and fixes that I can use to support students whenever they reach out to me with an issue.

**Acceptance Criteria**
FAQ documented as Jupyter Book, which includes the common issues and the fixes to support the Hub

**Tasks to complete**

- [x] Get the team's buy-in on the need to create a documentation
- [x] Collate commonly occurring issues across the ds-infrastructure list, GitHub issues, and slack channels into a [document ](https://docs.google.com/document/d/18DyQVsuAXHkHIqRtSvbJLNiu95lts39tTAi_MupcZPw/edit)
- [x] Get the team's inputs on the solution to various bugs
- [x] Publish the documentation as Jupyter Book version
- [x] Integrate this jupyter-book with the existing documentation  in DS-Modules repo

**Comment by ericvd-ucb** [comment]
and in addition - there is probably some documentation within the internal documents of Data 8 and Data 100 staff that have a lot of this .... but outside of that I would like this info to be here https://ds-modules.github.io/curriculum-guide/intro.html maybe in a new section called troubleshooting and support

**Comment by balajialg** [comment]
that sounds great @ericvd-ucb! Do you have access to the Data 8 and Data 100 documentation that I could repurpose?

**Comment by balajialg** [comment]
@yuvipanda @felder @ryanlovett Can you please take a look at this FAQ [document ](https://docs.ccv.brown.edu/jupyterhub/help-and-support/getting-support) whenever you have some free time?. It has a list of basic questions and issues GSI's/students might face while running hubs. I can start answering these questions based on the available information across ds-infra, slack, and GitHub issues if you all think the questions are comprehensive enough.

@ryanlovett To your question during the Tech Strategy meeting about the support process across different universities, 
Many universities didn't have extensive documentation of their support process. Brown had [one](https://docs.ccv.brown.edu/jupyterhub/help-and-support/getting-support), though, and it is more or less similar to the proposed support process,
Tier I: FAQ
Tier II: Slack or Discourse
Tier III: Email Id

**Comment by yuvipanda** [comment]
@balajialg can we convert the doc to a jupyter book and iterate there? The structure will probably be a bit different than what's possible in a google doc. 

Also I'm guessing the doc you wanted to link to is https://docs.google.com/document/d/18DyQVsuAXHkHIqRtSvbJLNiu95lts39tTAi_MupcZPw/edit (the current link in your comment also points to brown)

**Comment by balajialg** [comment]
Thanks, @yuvipanda for correcting the link! I am working on converting the document into a Jupyter Book. I will publish these changes asap!

**Comment by balajialg** [comment]
All, 

Created the first version of the [FAQ](https://balajialg.github.io/Datahub-Test-Repo/onboarding.html) Jupyter book! I would love for you all to review and share inputs wherever you feel the information needs to be tweaked.

**Comment by balajialg** [comment]
@felder Yes, If we all think that users discerning otter and Jupyterhub issues correctly is a consistent challenge and believe that there has to be a better way of doing this.
Then, I am thinking, why not have a common Tier I support system for otter and jupyterhub to start with. Then, if someone could parse such requests and redirect them to the relevant folks, that could be valuable for our users and for both the teams.

**Comment by balajialg** [comment]
Here is the link to the Updated FAQ for DataHub - https://ds-modules.github.io/curriculum-guide/index.html
