### ISSUE TITLE
Establish a process to get important workshop/event/assignment dates from varied hubs

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2589]
# Summary
Currently, we don't have a lot of visibility w.r.t. varied workshops, events, and deadlines across the courses and labs using datahub. Today, we had an issue with R Studio throwing 404 during a D-Lab workshop having 300 students causing a severe outage. We need to figure out a process to avoid such outages or increase our monitoring to respond better when such issues crop up during courses/events.

# User Stories
As a Team Member, I have access to all the important dates when a specific hub will get used for workshops/courses.

# Important information
D Lab's workshops are listed [here](https://dlab.berkeley.edu/training/upcoming-workshops)
(Need to get information from other courses/lab stakeholders)

# Tasks to complete

- [x] Identify courses using hubs having student count > 200
- [x] Identify the important dates from major hubs and calendar it
- [x] Ensure that major upgrades factor in these dates

**Comment by yuvipanda** [comment]
For big classes (everything with > 200 students, let's say) we should also get information on when their labs are, and when big homework is due.

**Comment by balajialg** [comment]
@yuvipanda Data 8 and 100 have their assignment dates listed publicly. I have added all the deadlines for these two courses to my calendar. I need to get this information for Data 140, Data 102, and Econ 140 too. Any other classes that I might have missed which have more than 200 students?
 
In terms of communicating these dates across the team, I thought of sending an invite to ds-infra. Any other suggestions to share this info effectively?

**Comment by yuvipanda** [comment]
@balajialg let's create a new Google Calendar and putting everything on that? That way, we can toggle the calendar on / off as needed.

**Comment by balajialg** [comment]
@yuvipanda Done. [Link ](https://calendar.google.com/calendar/embed?src=c_bs1c9i53hqrtjsb1psjdmpogtg%40group.calendar.google.com&ctz=America%2FNew_York)to the calendar

**Comment by balajialg** [comment]
@yuvipanda Considering your important work related to scheduling based on calendar events (https://github.com/berkeley-dsep-infra/datahub/pull/2681)  and insights from the latest [user research](https://docs.google.com/document/d/13T9iNH4TGLc7fHPmeGf02sxir9EFbVd5NlQuQS1w3oM/edit) with the infra lead for public health who highlighted scaling issues during a specific assignment, I am thinking of adding another process at the start of the semester (possibly a GitHub template) to get important dates for courses with a user count greater than 200 in this [list],(https://docs.google.com/document/d/13nhn7vHQpyq9ipgigHGRveL7hkcFswN9fdkCqhNlYTg/edit). Important dates could mean any of the following,

1. Compute resources required before the deadline for a specific assignment(s) will be high  (Eg: Data 8 assignments requiring simulations)
2. Live workshops (Eg: D-Lab R workshops reaching 300+ people synchronously)
3. Flipped teaching classes where instructors want students to work on assignments in groups (Eg: Pol Sci 3)

Would it be possible to schedule this prior to the start of the spring semester?

Kept 200 as an arbitrary number so that we can manage this process effectively. If you think the threshold should be much lower then do let me know!

**Comment by balajialg** [comment]
Created the required template to get such details from compute-heavy courses! Let's operationalize this during our outreach to the faculty next semester.
