### ISSUE TITLE
Datahub Home Page Redesign!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2823]
# Summary

Our [Home page](http://datahub.berkeley.edu/) requires some love! Assuming that most of our users are not going to visit this page (thanks to the SSO), It is important to revisit who this page is designed for. I believe that the home page could target two different audiences,

- **Leadership:** We can share key metrics/updates about Datahub to the leadership (RTL, CDSS, and IS&T) and interested stakeholders through this page!
- **Future instructors:** We can share case studies of different courses using the hub & support process for future instructors!

# User Stories

- As a leader, I want to visit the home page of Datahub so that I can understand the key metrics and track the growth of the tool.
- As an instructor, I can learn about how different instructors use Datahub across different domains/courses

# Acceptance criteria

- Given a need to understand key metrics/case studies about Datahub, when users pull up the home page then they can get all the required information

# Tasks to complete
- [ ] @yuvipanda to figure out a hack to pull the drupal page as the home page for Datahub
- [ ] Replace the old logo with the new logo~
- [x] - Balaji to create a Figma/Adobe XD a version of a mockup that curates the information required for these 2 audiences
- [x] - Balaji to figure out whether a designer could be used to create design collaterals for the home page (which includes logo, banner, slide background, etc..)
- [x] - Work with the designer to get the final assets
- [x] - Publish the changes into the live version of the home page
**Next Steps from 3/24 meeting:**
- [x] @balajialg to figure out ways to add i) Datahub's Call to Action (CTA) and ii) list different types of hubs on the web page

**Comment by balajialg** [comment]
Link to a couple of mock-ups created (version 1.0)!
[Mockup #1.0
](https://www.figma.com/file/Pfl9MzAHqYbbIxfSIK5QFE/Datahub-Home-Page-Mockup?node-id=0%3A1)
[Mockup #2.0
](https://www.figma.com/proto/UuyryWiJqljOnAtxNrXDHi/Datahub-Mockup-2.0?page-id=0%3A1&node-id=2%3A436&viewport=241%2C48%2C0.13&scaling=min-zoom)

**Comment by balajialg** [comment]
Flint (Designer) from RTL is interested to support this effort. Balaji to meet with Flint to walk through the design requirement.

**Comment by balajialg** [comment]
@yuvipanda is exploring the usecase of integrating a [flat-file CMS](https://www.cmscritic.com/top-flat-file-cms-platforms-for-building-simple-websites-fast/) into Jupyterhub. 

In parallel, RTL designer flint is working on creating wireframes and additional design assets for the home page. Once the design assets are created AND the CMS gets integrated into Datahub, I will either work independently or with a student developer to build this page. Hope is that both the assets and the CMS integration happen by mid-January so that this web page gets built by mid/end Feb 2022.

**Comment by yuvipanda** [comment]
@balajialg great! For a february launch, I think the work should go into modifying https://github.com/berkeley-dsep-infra/datahub-homepage to fit the use case (there are docs on how to test it locally there). I don't think we should block on the CMS work for february.

**Comment by balajialg** [comment]
@yuvipanda Ah got it. That definitely helps from an execution standpoint. Is it possible to maintain this page through a CMS whenever it gets integrated?

**Comment by balajialg** [comment]
@ryanlovett Had a conversation with Anthony and Chris about the potential options to build the website (Listed the choices we came up with). 

Anthony liked your idea of building this page as part of the new CDSS [website ](https://live-computing-data-science-and-society.pantheon.berkeley.edu/node/147) which is currently built in drupal. He shared the required credentials for the new website and I am mostly playing with it. Hopefully, will use the next few weeks to build this page (assuming I will get the required design collaterals from Flint). Thanks for all your help!

**Comment by balajialg** [comment]
Published the initial version of home and support web page,

- https://data.berkeley.edu/datahub-home
- https://data.berkeley.edu/datahub-setup

Need to seek the support of Drupal developers and Flint (designer) to improve the design/layout of the web page.

**Comment by balajialg** [comment]
@yuvipanda Please feel free to add any next steps from this meeting that I missed adding to the above list.

**Comment by balajialg** [comment]
Final assets created during this sprint by Flint! Aren't these logos amazing?
![datahub-logo-filled-edge-link](https://user-images.githubusercontent.com/2306166/163249092-eb6c449e-1116-4ad3-923a-dd19e4cf1f8a.png)
![datahub-logo-filled-inside-link](https://user-images.githubusercontent.com/2306166/163249100-f9f854ba-d72c-410f-929d-ae5a47b2a607.png)
![datahub-logo-outline-inside-link](https://user-images.githubusercontent.com/2306166/163249102-3ed5a61c-2c41-4281-97ef-cfc9ebbdf729.png)
[Data Hub Logos.zip](https://github.com/berkeley-dsep-infra/datahub/files/8483893/Data.Hub.Logos.zip)
![datahub-logo-filled-white](https://user-images.githubusercontent.com/2306166/163249244-59029346-4b71-4e85-bfba-f1d40d6b9c50.svg)
![datahub-logo-outline-dark](https://user-images.githubusercontent.com/2306166/163249247-8a6fcead-6200-4c27-a56b-5237b05ff222.svg)
![datahub-logo-outline-orange](https://user-images.githubusercontent.com/2306166/163249251-dbdd4cd8-5cc6-4abc-b91a-8b7480fa11d5.svg)
![datahub-logo-outline-white](https://user-images.githubusercontent.com/2306166/163249253-bd0d6626-bc43-4705-accf-33e1f8aec8a0.svg)
![datahub-logo-filled-dark](https://user-images.githubusercontent.com/2306166/163249258-21bb27e4-ca87-4740-9244-5dba83ae0ff7.svg)
![datahub-logo-filled-orange](https://user-images.githubusercontent.com/2306166/163249261-6b325a65-8a01-4426-9dac-aa58954c22da.svg)

**Comment by balajialg** [comment]
Updated logos where jovian bear is tilted southwest based on @ericvd-ucb's feedback
![datahub-logo-outline-dark](https://user-images.githubusercontent.com/2306166/163634329-da06a51b-be06-4650-8ca5-cfeb4a893115.svg)
![datahub-logo-outline-orange](https://user-images.githubusercontent.com/2306166/163634330-81e9a4bb-ff74-4b49-b0b3-1635365a4a1f.svg)
![datahub-logo-outline-white](https://user-images.githubusercontent.com/2306166/163634331-24322641-d931-4b98-bc44-4d076f081d8d.svg)
![datahub-logo-filled-dark](https://user-images.githubusercontent.com/2306166/163634332-abd98c3d-16fe-44f0-b852-a075eeddc6fa.svg)
![datahub-logo-filled-orange](https://user-images.githubusercontent.com/2306166/163634333-62dfe49e-a17f-44d9-a900-2a70ad95356e.svg)
![datahub-logo-filled-white](https://user-images.githubusercontent.com/2306166/163634334-002b4c01-30e8-44d0-af98-c5e76dd72aa3.svg)
