### ISSUE TITLE
Exploring the idea of Monthly Newsletter for Datahub! 

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2855]
# Summary

In our sprint planning and retrospective discussion today, we had this suggestion to showcase our work in an effective way by creating communication collaterals on a monthly basis. We need to figure out who the target audience is, what kind of information they need, how can we reach them easily, and the frequency of this communication? 

Created this issue to explore the idea of creating a monthly newsletter. 

# Tasks to be done:

- [x] Brainstorm ideas with @ericvd-ucb to figure out the audience, format, and content for this newsletter
- [x] Get the team's inputs for the first newsletter
- [x] Figure out the audience for the newsletter
- [x] Communicate using available outreach mechanisms!

**Comment by yuvipanda** [comment]
Was just looking at to see what sections we would have if we had such a newsletter from https://github.com/berkeley-dsep-infra/datahub/projects/3.

## Major changes

- `ftp` and all outbound traffic now open! https://github.com/berkeley-dsep-infra/datahub/issues/2825
- Julia hub now has Julia 1.6 https://github.com/berkeley-dsep-infra/datahub/issues/2803
- Python package changes: (list additions and removals, if we want to)
- R package changes: (list additions and removals, if we want to)
- We are now installing packages from conda instead of pip, should have no user facing impact but future package upgrades should be smoother - https://github.com/berkeley-dsep-infra/datahub/issues/2934
- We can also add some usage stats

**Comment by balajialg** [comment]
Quick update: Had a fruitful discussion with the DSUS team about designing a newsletter to highlight some of the data science work across modules, otter, jupyterhub, connector, etc... Will make iterations on this idea further during the upcoming weeks.

**Comment by balajialg** [comment]
@ericvd-ucb @yuvipanda Thoughts about having a monthly newsletter with a similar [template](https://balajialg.substack.com/p/e2cc20f2-8b8b-4109-808e-c56840856395)? Worth discussing during the next week's mini DSUS meeting?

**Comment by balajialg** [comment]
Run a pilot for 3 months to see if the teaching team finds our newsletters useful. Success metric in my head is that 200+ folks read the newsletter and 10+ folks reacted positively to the information that was being shared. If we are nowhere closer to this metric by the end of March, we can stop this initiative. The goal is to publish information during the second week of every month.  Please comment if you think there are better metrics to measure our success?

**Newsletter Plan for January:**
- Publish a substack newsletter by the 2nd week of January (Between Jan 12th - 14th, 22)
- Get @yuvipanda's inputs on the newsletter worthy product updates for Datahub, @ericvd-ucb's inputs on Modules and Otter grader updates and Discovery related updates from Arlo
- Create a case study of how Brockman used the Datahub/Otter Grader combination to run his 300+ students classroom in Political Science synchronously
- Highlight the major workshops happening during the month of January
- Share the newsletter through CDSS, RTL, DLab newsletters, and also the ds-infra list (#2197) created by the team

**Comment by balajialg** [comment]
Newsletter for Jan is out - https://ucberkeleydatahub.substack.com/p/january-edition-of-berkeley-datahub

Have 10+ subscribers and 65+ views as of now. Need to work on further outreach going forward.
