### ISSUE TITLE
Track Jupyter Lab and Notebook Accessibility

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3074]
# Summary
Creating this issue to formulate our goals & actionable next steps for what accessibility looks like in Datahub and potential upstream improvements that need to be made to ensure that the service hits the defined [campus accessibility milestones](https://docs.google.com/spreadsheets/d/1oL4HyTr2EibU2eaNsymFWwO4pu36zbFAGzbdH186t1U/edit#gid=949844770). One of the key stakeholders interested in Datahub hitting this milestone is RTL leadership, who have been vocal about us putting extra effort to improve tool's accessibility. 

However, as we all know, **we don't control the end-user experience** of any of the Jupyter tools - Classic Notebook, Jupyter Lab, and Retro Lab. Considering this reality, we must actively evaluate the campus requirements, track whether those improvements get logged in relevant GitHub repositories, and track their development journey. If issues did not get tracked upstream, raise relevant GitHub issues in the respective repository so that the key stakeholders in the Jupyter ecosystem know this need. The main repository that tracks all the accessibility-related efforts in Jupyter is the [Accessibility Repo](https://github.com/jupyter/accessibility). 

Individual repositories tracking accessibility-related stuff include the following repositories,

- [Classic Notebook](https://github.com/jupyter/accessibility)

- [JupyterLab](https://github.com/jupyter/accessibility)

- [Jupyterhub](https://github.com/jupyter/accessibility)

How can we integrate with the upstream work happening in the Jupyter ecosystem to achieve the accessibility goals? Our current strategies are,

- Be an early tester for Jupyter Lab 4.0 pre-release version. Deploy this version as part of a new hub and test for CM 6.0 changes pushed by QuantStack.
- Share our goals with the timeline for the Quantsight folks. Support them interim in order to achieve the set goals.

# Useful Documentation

- Quantsight roadmap for adding accessibility-related updates - https://github.com/orgs/Quansight-Labs/projects/5/views/5

- Quantstack PR for upgrading to Code Mirror 6.0 - https://github.com/jupyterlab/jupyterlab/pull/11638

- Datahub Accessibility Audit - https://docs.google.com/spreadsheets/d/1kpOUkYmy3p4rKiQW72cgrK1HZ_PlVsD2Px60lMGsbms/edit#gid=492520477

- Datahub Accessibility short-term plan - https://docs.google.com/document/d/1_E9Q7bhx2vMwO0LnQS5YLJCszXYrNsgm4HkjooX_-Lw/edit?usp=sharing

# Tasks to complete

- [x] Set up a new hub to test Jupyter Lab 4.0 pre-release version which contains the latest update to the Code Mirror editor @yuvipanda
- [x] Share Berkeley's accessibility goals + timeline with Quantsight folks
- [ ] Test Jupyter Lab 4.0 when it releases in a11y hub
- [ ] Test Jupyter Notebook 7.0 when it releases in a11y hub
- [ ] Support Data8x edx course relaunch

**Comment by balajialg** [comment]
@ericvd-ucb @yuvipanda Notes from [12/16 Accessibility Workshop](https://docs.google.com/document/d/1WujryJMir5dcgyyiMMlmpV3DkUamwdry3Jwo3Ytmvbs/edit?usp=sharing)! As @ericvd-ucb suggested, The next step would be to summarize the learnings about the accessibility improvements happening across the Jupyter ecosystem into a memo that could get shared with the leadership!

**Comment by ryanlovett** [comment]
@yuvipanda suggested in previous conversation that before the web accessibility clinic reviews datahub again, we should wait for jupyterlab to integrate the new [CodeMirror](https://codemirror.net/) editor ([version 6](https://codemirror.net/6/) I presume which "was designed from the start with accessibility in mind"). Otherwise we are likely to see similar results as before.

**Comment by ryanlovett** [comment]
Here is the jupyterlab issue for integrating CodeMirror 6, https://github.com/jupyterlab/jupyterlab/issues/10370.

**Comment by balajialg** [comment]
@ryanlovett Thank you so much for circling back on the Code Mirror editor integration in Jupyter Lab. I went with the assumption that Code Mirror 6.0 was already integrated into the core interface which is not true as you clearly pointed out. 

Your suggestion to wait till the CM 6.0 integration makes sense as already there are GitHub issues [#1](https://github.com/jupyterlab/jupyterlab/issues/9399) and [#2](https://github.com/jupyterlab/jupyterlab/issues/911) from partner institutions which clearly documents the results from varied accessibility audit of Jupyter Lab. In high probability, we may not be adding anything new/novel to the conversation happening in this space. 

However, I have a couple of questions/concerns,

- There is no proposed timeline for this integration which makes it hard to know when to scope the campus accessibility audit.
- No sign of CM 6.0 upgrade in[ Github issues](https://github.com/jupyterlab/retrolab) for the retro lab (and classic notebook). Does that mean, any upgrade happening in the Jupyter Lab repo gets automatically ported into the retro interface?

I will not reach out to the accessibility audit team in the near future and wait for more clarity regarding CM 6.0 integration with retro lab & jupyter lab.

**Comment by yuvipanda** [comment]
> No sign of CM 6.0 upgrade in[ Github issues](https://github.com/jupyterlab/retrolab) for the retro lab (and classic notebook). Does that mean, any upgrade happening in the Jupyter Lab repo gets automatically ported into the retro interface?

Yep, anything that happens in retrolab wrt the notebook UI, text editor UI, terminals, and file browsers automatically works in retrolab.

**Comment by balajialg** [comment]
FWIW, Siteimprove gave an accessibility score of 94.3 for the datahub.berkeley.edu page. 
![image](https://user-images.githubusercontent.com/2306166/163659689-33127030-8148-40bf-ab5f-426b11a1caf6.png)

**Comment by ryanlovett** [comment]
@balajialg That's great! It's probably very high since it didn't evaluate notebook or lab, but at least it means the landing page doesn't have a lot of problems.

**Comment by balajialg** [comment]
@ryanlovett Not sure how I missed your comment! It makes sense. As a next step, I am trying to do the Siteimprove audit for [the new datahub](https://data.berkeley.edu/datahub) page and add recommendations for the black antelope team to work on.

**Comment by balajialg** [comment]
- [ ] Check a11y image for versions of JN and JL

**Comment by balajialg** [comment]
[Beta version (4.0.0b0) ](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b0) of Jupyter Lab 4.0 (JL 4.0) which is the pre-release version for Jupyter Lab released a couple of days ago. The beta version of Jupyter Notebook 7.0 (JN 7.0) is currently a work in progress at the time of writing but we have the [latest alpha version of JN 7.0](https://github.com/jupyter/notebook/milestone/45) (Version 7.0.0a18) which can be audited.

To track the progress of a11y changes, I am comparing the results of running the Axe Deque tool against Jupyter Lab version 3.4.5, Retro Lab version 0.3.21, and Classic Notebook version 6.4.2 which were previously installed in [Data 100 hub image](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100/image/infra-requirements.txt) against the latest releases which were[ installed in a11y hub](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/a11y/image/environment.yml). Note that the current releases only have Jupyter Notebook 7.0 and Jupyter Lab 4.0 as Classic Notebook interface did not get the a11y updates and will not be supported after 2 years and Retro Lab interfaces got renamed as JN 7.0.

To make the comparison apples to apples, I used the [demo notebook for lecture 2](https://ds100.org/sp23/lecture/lec02/) from Data 100 course work during Sp 23 for the a11y audit.

Sharing the snapshot of the results and the spreadsheet with issues generated from running automated a11y check using Axe Deque tool for,

## Classic Notebook version 6.4.2

![image](https://user-images.githubusercontent.com/2306166/228644655-49dbcb39-26e8-4308-9ee1-67587bf84f7d.png)

[data100.datahub.berkeley.edu-2023-03-29.csv](https://github.com/berkeley-dsep-infra/datahub/files/11104776/data100.datahub.berkeley.edu-2023-03-29.csv)

Here is the snapshot of the results and the spreadsheet for 

## RetroLab version 0.3.21

![image](https://user-images.githubusercontent.com/2306166/228645367-da8c41bc-0e4e-4b17-979b-55977292690d.png)

[data100.datahub.berkeley.edu-2023-03-29.csv](https://github.com/berkeley-dsep-infra/datahub/files/11104780/data100.datahub.berkeley.edu-2023-03-29.csv)

Here is the snapshot of the results and the spreadsheet for 
## JupyterLab version 3.4.5

![image](https://user-images.githubusercontent.com/2306166/228645680-9264dbe2-b01c-45bf-91d5-6c45c8654d17.png)

[data100.datahub.berkeley.edu-2023-03-29 (1).csv](https://github.com/berkeley-dsep-infra/datahub/files/11104787/data100.datahub.berkeley.edu-2023-03-29.1.csv)

Now, sharing the snapshot of the results and the spreadsheet for the latest 

## Jupyterlab version 4.0.0b0
![image](https://user-images.githubusercontent.com/2306166/228646175-2b6348d6-1df9-42a9-b707-58cf2bfa648a.png)

[a11y.datahub.berkeley.edu-2023-03-29 (1).csv](https://github.com/berkeley-dsep-infra/datahub/files/11104796/a11y.datahub.berkeley.edu-2023-03-29.1.csv)

Sharing the snapshot of the results and the spreadsheet for 

## Jupyter Notebook version 7.0.0a18

![image](https://user-images.githubusercontent.com/2306166/228646122-640375b9-1384-425e-a5c4-dd63ce546e21.png)

[a11y.datahub.berkeley.edu-2023-03-29.csv](https://github.com/berkeley-dsep-infra/datahub/files/11104791/a11y.datahub.berkeley.edu-2023-03-29.csv)

**Comment by ericvd-ucb** [comment]
Wow  thanks @balajialg this is really hopeful!

**Comment by balajialg** [comment]
### Keyboard test results for JL 4.0:

![image](https://user-images.githubusercontent.com/2306166/229949805-41c7cb32-07e0-4d8b-bf81-29006a23eed8.png)

### Keyboard test results for JN 7.0:

![image](https://user-images.githubusercontent.com/2306166/229950094-49fdebe6-e93a-47ae-a14f-f763d4544cc4.png)

**Comment by balajialg** [comment]
### Open issues with screen reader testing using nvda:

I installed the latest version of nvda ([nvda version 2023](https://www.nvaccess.org/download/)) in my local device and allowed it to decipher a [notebook ](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-sp23&urlpath=retro%2Ftree%2Fmaterials-sp23%2Fmaterials%2Fsp23%2Flab%2Flab03%2Flab03.ipynb&branch=main)from Data 8 course,

- Screen reader did not decipher text included in images without accessible text (as seen in the snapshot below),
![image](https://user-images.githubusercontent.com/2306166/229951634-e052603f-30d3-4520-a5f5-e3a23e944461.png)
- Screen Reader did not decipher the output of running a code block (as seen in the snapshot below),
![image](https://user-images.githubusercontent.com/2306166/229951595-2cd530de-2f6c-4a6c-8ca5-a113330b6a0b.png)
- Screen Readers did not identify icons (as seen in the snapshot below),
![image](https://user-images.githubusercontent.com/2306166/229951697-0075bd69-2660-4917-a462-99c12d156f8f.png)

**Comment by balajialg** [comment]
Tagging @jtpio - Feedback shared from testing beta versions of JL 4.0 and JN 7.0 using Axe Deque and Nvda in the previous comments. Hoping that you are aware of some of the issues highlighted above.

**Comment by jtpio** [comment]
Thanks @balajialg for the ping.

Also cc @brichet who has been helping with accessibility in JupyterLab and Notebook 7.

**Comment by brichet** [comment]
Thank you for sharing these tests @balajialg
