### ISSUE TITLE
[EPIC] Test Jupyter notebooks during GitHub action builds

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3220]
# Summary

Testing Jupyter notebooks during CircleCI CI/CD builds are an important part of making the infrastructure more resilient. We had multiple outages where users reported issues with the infra even before we were aware. These issues were due to upgrades made to some of the packages in PyPi/Jupyter ecosystem. 

Already there are multiple implementations at the Jupyterhub level (https://github.com/jupyterhub/repo2docker-action/pull/83), 2i2c infrastructure level (https://github.com/2i2c-org/infrastructure/issues/879) and in fact, there is a [Github action](https://github.com/marketplace/actions/repo2docker-action) which tests notebooks during the CI/CD builds. We should figure out a way to implement a proof of concept that [tests notebooks](https://github.com/marketplace/actions/repo2docker-action#test-image-build) in our infrastructure.

## Tasks to be done:

- [ ] Develop a proof of concept in Circle CI to test Jupyter notebooks

**Comment by balajialg** [comment]
Test Suites for automated testing and Policy for the new hub are the priority items for February!

**Comment by balajialg** [comment]
**Next Steps from March Sprint Planning Meeting:**
- [x] Split out Stat 159  docker image into its own repository and add separate test suites
- [x] Standardize test process for all different processor types (@felder to detail this out). @yuvipanda to document the approach!
- [x] Review the monitoring infrastructure - Grafana, Prometheus, and Pagerduty together as a team

**Comment by balajialg** [comment]
@yuvipanda @felder Updated the next steps from our discussion in this Github issue!
