### ISSUE TITLE
Issue with filenames of logs data stored in GCP buckets!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3356]
# Summary

As part of my exploration in #3267 and #2949, My objective is to read the log data to capture general trends with 
i) Courses using Datahub during Spring 22 (For our Tech strategy meeting this week) and 
ii) Features commonly used by courses across both semesters. 

I ran a few queries using [log explorer](https://cloudlogging.app.goo.gl/7dJ5diUcv4mcFB6U8) across the 30-day log data to achieve this objective. After formulating the required queries, I wanted to run them across long-term data (in the range of 4 -12 months). I had a conversation with @felder today to seek his input to achieve this objective. We realized that, based on our current policy, it is not possible to explore trends beyond 30-day data as the default storage limit for logs explorer was 30 days. Thankfully, @felder generously increased the storage limit to 6 months after confirming that it is not drastically increasing the cloud costs. Storing additional logs is [free till October 2022](https://cloud.google.com/stackdriver/pricing) and will cost $0.01 per GB for additional logs post-October 2022

However, this change only ensures that data accumulated over the next 6 months will get stored in log explorer but the previous data will not get retrieved. Considering that exploration through log explorer is not feasible in the near term, I followed @yuvipanda's inputs in [this issue](https://github.com/berkeley-dsep-infra/datahub/issues/2949#issuecomment-975134163) which recommends using the gsutil command to download all the logs data for the year 2022 from the GCP buckets. However, when I ran the query `gsutil -m cp -r gs://ucb-datahub-hub-logs/stderr/2022 .` on my windows machine, it failed by throwing an "invalid filename error". Apparently, @felder confirmed that this error is due to the naming convention followed in the JSON files. It was clear that storing JSON files with a filename having a colon is causing the gsutil download command to fail. We currently name the JSON files with timestamp data (like 00:00:00_00:59:59_S0.json) which is not an acceptable character as per Windows [file naming convention](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file).  

Please do let me know if there are better ways to work around this challenge. 
# User Stories

- As a `hub infra team member` I want to `analyze the logs data` so that `I can get insights into courses using Datahub and commonly used features`.

# Tasks to complete
Proposed recommendations to ensure that logs data is retrievable in Windows machine!

- [ ] 1. @yuvipanda to modify the script which writes logs data to the GCP bucket to avoid colons as part of the JSON file names.
- [ ] 2. Once the above change gets merged to the code base, @felder to write a script to modify existing buckets' JSON file names to avoid colons.
- [ ] 3. In addition, @felder suggested a long-term option of using[ Big Query](https://cloud.google.com/bigquery) to explore the log data. It will be great if we can find an option where we can run queries in the cloud without having to handle the hassle of downloading files to the local machine (Considering that last 4 months worth of data alone is accumulating to ~160 GB)

**Comment by felder** [comment]
One solution to this issue that may not require any changes to filenames would be to use WSL and mount an ext4 filesystem.

https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk
