### ISSUE TITLE
Standardize hub storage directories on nfsserver-01

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/hubs#3380]
# Summary

We have a few filesystems containing home directory information for the various hubs and currently the directory structure for these filesystems is not standardized.

We should standardize them as follows:

/export/filesystem/hub/prod|staging/userdirs

Examples for what I'd like to see: 
datahub prod
/export/datahubhomes-2020-07-29/datahub/prod

datahub staging
/export/datahubhomes-2020-07-29/datahub/staging

data100 prod
/export/data100homes-2020-08-04/data100/prod

eecs staging
/export/homedirs-other-2020-07-29/eecs/staging

In cases where we need prod and staging to share the same files, we can point staging's config to prod's files.

# User Stories

As a sysadmin storage management/archiving/analysis would be easier if storage locations were standardized.

# Acceptance criteria

All hubs use the storage path spec as described above.

# Important information

The following is a list of hubs that currently do not follow this structure:

datahub 
data100 
highschool/buds-2020 
cs194 
data102 
dlab 
eecs
biology/genomics
julia
prob140
stat89a
workshop

hubs that do follow this structure:
ischool
astro
data8
stat159
stat20

# Tasks to complete

- [x] Move/rename storage subdirectories as necessary.
- [x] Change hub configs to match and redeploy
- [x] move data8 to it's own disk using standard tier

**Comment by ryanlovett** [comment]
I love the notion of standardizing this! Just one observation which is that the format `/export/{hub}homes-{date}/{hub}/{branch}` duplicates `{hub}` in 3/4 of those instances.

**Comment by felder** [comment]
@ryanlovett I think that makes sense because generally the filesystems match the names of their persistent disks as labeled in gcp.  For disks that contain a single hub such as datahub, it makes sense for the labeling to reflect that.  If filesystems are going to contain multiple hubs, there will need to be subdirs for those hubs.  If a filesystem contains a single hub, there should still be a subdir for it.  That means yes, there might be some redundancy in naming.

**Comment by felder** [comment]
data8 is is 1.4TB

I have provisioned a 3TB standard disk for data8 and I'm going to perform start the rsync data transfer

**Comment by yuvipanda** [comment]
Thanks a lot, @felder!

For the rest, I think we can use symlinks to do the changes without any downtime. As they'll be within the same filesystem, `mv` is atomic. So something like `mv <cur-location> <target-location> && ln -s <target-location> <cur-location>` should mv the directory to the correct location, and setup a symlink in the previous location.

We can then 'normalize' the paths in helm config, and eventually remove the symlinks.

**Comment by felder** [comment]
Ok all of this work is done!

**Comment by balajialg** [comment]
Thanks for the awesome work @felder!
