### ISSUE TITLE
Set up hub for Data 101: Data Engineering course(Fall 2022)

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3513]
# Summary

Email from the instructor highlighting his requirement for Fall 2022,

_My name is Lakshya and I am the instructor for Data 101: Data Engineering. This course is a version of CS 194-35, which Allen Shen told us you helped them set up a Datahub for. Could we have the exact same setup as they had in Spring 2021 for CS 194-35?  please let us know if you need anything else from us. Replicate the same setup with Postgres server per student and maybe eventually the same for MongoDB_

# User Stories

- As a `Data 101 instructor` I want to `use the same hub set up as CS194-34` so that `students can explore Postgres/MongoDB database>`.

# Important information

The instructor wants this request to be completed before Aug 15th, 2021 so that he can do testing at his end. @ericvd-ucb  highlighted that this course is going to be one of the core Data courses (link to previous semester - https://cal-data-eng.github.io/) 

# Tasks to complete

- [ ] Create a new hub for Data 101 ??
- [ ] Instructor tests to verify whether these requirements are met

**Comment by balajialg** [comment]
CS 194 Hub creation issue - https://github.com/berkeley-dsep-infra/datahub/issues/2116
CS 194 Hub decommission issue - https://github.com/berkeley-dsep-infra/datahub/issues/2622

**Comment by balajialg** [comment]
**Next Steps from 08/04 Sprint Planning Meeting:**
- [x] @yuvipanda to set up the hub!

**Comment by balajialg** [comment]
@yuvipanda Do you want to prioritize this request from the instructor? He highlighted that August 15th is a good timeframe to start testing the new hub.

**Comment by yuvipanda** [comment]
I'll try get it done before 18th.

**Comment by balajialg** [comment]
Closing this issue as @yuvipanda created a new hub with postgres DB!
