### ISSUE TITLE
Shane Onboarding: Datahub Infra Access Checklist

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#3820]
I am creating this issue to track whether all the required access details got provided to Shane. @felder Please feel free to add if I had missed any,

- [x] Berkeley-dsep-infra admin access
- [x] Grafana admin access
- [x] Circle CI access
- [x] GCP access
- [x] ds-infrastructure listserv access
- [x] Pagerduty access
- [x] Google Auto Scaling calendar access
- [x] Infoblox
- [ ] run prometheus locally

**Comment by felder** [comment]
Access granted to all of the above...I think. :)

Let's keep this open a for a bit in case anything was missed or something doesn't work.

**Comment by balajialg** [comment]
Fantastic, Thanks @felder for the quick turnaround!

**Comment by ryanlovett** [comment]
I also gave him access to the Data Science Computing Infrastructure shared drive owned by ds-instr@berkeley.edu.

**Comment by shaneknapp** [comment]
woo!

**Comment by shaneknapp** [comment]
ill double-check everything tomorrow...  thanks for putting this together, @felder !

**Comment by shaneknapp** [comment]
devops trello board(s)?

**Comment by ryanlovett** [comment]
There was an ancient (2016) trello board, but @balajialg has been using GitHub Projects for sprint planning.

https://github.com/berkeley-dsep-infra/datahub/projects?type=classic

I just closed out the ancient one which had me, Denero, Lau, and Anderson-Lee (from the local cluster semester!).

**Comment by balajialg** [comment]
@shaneknapp I was thinking of sharing these requirements with you when most of Yuvi's sessions are completed. Listed below is a bunch of github issues that are out there capturing varied requirements - mostly long-term infrastructure changes. We wanted to prioritize these use cases for a long time but lacked the technical bandwidth to drive execution. They were curated a few months back so there might be a few additions/deletions. It will be helpful if you can review these issues during your free time and get some context.

**High-Priority Use Cases:**

- [ ] 1. [Adding Test suites to CI/CD](https://github.com/berkeley-dsep-infra/datahub/issues/2953)
- [ ] 2. [Improved Alerts](https://github.com/berkeley-dsep-infra/datahub/issues/2693) and Strengthen Grafana dashboards ([#1](https://github.com/berkeley-dsep-infra/datahub/issues/2812), [#2](https://github.com/berkeley-dsep-infra/datahub/issues/2942) and [#3](https://github.com/berkeley-dsep-infra/datahub/issues/3267))
- [x] 3. [Investigate Cloud Costs](https://github.com/berkeley-dsep-infra/datahub/issues/3518) 
- [ ] 4. [Automate data requests](https://github.com/berkeley-dsep-infra/datahub/issues/2898)

**Medium Priority Use Cases:**

- [x] 1. [Estimate cloud costs for all hubs at per node level](https://github.com/berkeley-dsep-infra/datahub/issues/3019)
- [ ] 2. [Reduce image build time](https://github.com/berkeley-dsep-infra/datahub/issues/2946)

**Comment by shaneknapp** [comment]
awesome, thanks balaji!  i'll take a look at these tomorrow.

**Comment by balajialg** [comment]
@shaneknapp Please reopen this issue if it is relevant.
