### ISSUE TITLE
[EPIC] Improvements to Auto Scaler and Node Scaler

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4200]
# Summary

Identify ways to optimize auto scaler = scale ups and downs in order to bring down cost. We currently scale nodes based on memory consumption, assuming some fixed amount per user. When the spawner realizes that all nodes are full of users, it schedules another to spin up. This can be slow because nodes have to pull down docker images. To speed things up sometimes we spin up spare nodes in advance. 

# User Stories
As a system administrator, I can configure auto-scaler to spin up and spin down nodes without a considerable delay

# Acceptance criteria
Node spin ups and spin downs should be fast and less disruptive

# Tasks to complete

- [ ] Investigate the [k8s autoscaler](https://github.com/kubernetes/autoscaler).

**Comment by balajialg** [comment]
- [ ] Improvements to node scaler to reduce cost
- [ ] Improvements to calendar based auto scaler to handle exceptions

**Comment by balajialg** [comment]
@ryanlovett @felder Might need your help to flesh out this use case.

**Comment by ryanlovett** [comment]
We currently scale nodes based on memory consumption, assuming some fixed amount per user. When the spawner realizes that all nodes are full of users, it schedules another to spin up. This can be slow because nodes have to pull down docker images. To speed things up sometimes we spin up spare nodes in advance.

We should investigate the [k8s autoscaler](https://github.com/kubernetes/autoscaler).

**Comment by balajialg** [comment]
Thanks @ryanlovett! Appreciate it.
