### ISSUE TITLE
Enable Jupyter-Octave in Experimental hub 

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4273]
# Summary

A Civil Engineering instructor recently explored the idea of using Matlab through one of RTL's services and couldn't find the right fit. I realize that this is a good opportunity to evangelize a new use case to the instructor related to Matlab/Octave in Datahub . The open-source nature of Octave GNU makes me prefer Octave kernel over [Matlab](https://blogs.mathworks.com/matlab/2023/01/30/official-mathworks-matlab-kernel-for-jupyter-released/). We currently need a mechanism to showcase how instructors can use the [Octave kernel](https://github.com/Calysto/octave_kernel) in Jupyter notebooks. 

This would help showcase pathways for instructors who use Octave/Matlab to use Jupyter notebooks and could be yet another additional use case for Datahub.

# User Stories

- As an instructor I want to showcase  how to use Octave using Jupyter notebooks with my students so that they can run numerical computing using Datahub (without buying subscription from Matlab).

# Acceptance criteria

- User launches Jupyter Notebooks with Octave kernel 

# Tasks to complete

- [ ] Choose a hub to deploy Octave kernel (Possibly a11y hub?)
- [ ] Add the kernel to the image
- [ ] Test the features in staging hub before deploying to prod
- [ ] Evangelize with the requested instructor

**Comment by balajialg** [comment]
@ryanlovett commented in slack

_Putting octave in a11y and using that for testing... I think we had decided that we'd create separate hubs for separate big features. Iirc, the reasoning was that if someone wanted to test one feature, it should not impact the experience of those testing another feature. For example it could be that the a11y dependencies on alpha versions of lab/notebook will get in the way of testing the octave kernel. So i'd vote in favor of having a separate octave hub (that would use the small hubs storage).
However, if I understood that wrong and we are to have one hub set aside for experimentation, then we should call it experiments.datahub or x.datahub, and then enable multiple environments. I think we could use the [profile_list](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.profile_list) feature of kubespawner and then prepare multiple profiles. For example one could start up a a11y image another could startup an octave 
image, etc. People would see a form when they login to the hub and could choose which to experiment with_

**Comment by ericvd-ucb** [comment]
I feel like we really dont know if anyone would use an Octave Hub?  Seems like we need to find the instructor / Use case before developing too much time on it

**Comment by balajialg** [comment]
@ericvd-ucb We do know that an instructor wanted to use Matlab/Octave for their course in a cloud based set up. They reached out to the LET team within RTL for this request. The usecase here is also well defined atleast from a dev standpoint. Enabling octave in Jupyterhub would involve tweaking the image to add an entry as specified [here](https://github.com/Calysto/octave_kernel). 

I don't think this use case specifically deserves a hub. If there is an experimental hub, then we can just tweak the image to enable this functionality. In my head, it seems like a low hanging fruit that could potentially usher in a new user. Evangelizing something new that doesn't exist is hard compared to having a proof of concept. I see this use case fall into the category of a proof of concept. Once again, this is a nice to have than a must have and I guess there is a shared consensus within the team regarding that view.
