### ISSUE TITLE
Plan for hubs that are not used this semester!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4313]
# Summary

Last week's investigation revealed that Data 101 hub had postgres and mongo db PVC's mounted even while not being used this semester. I reached out to the Fall 22 Data 101 instructor Lakshya Jain who confirmed that he is not teaching this semester using this hub. Lisa Yan who plans to teach Data 101 during FA 23 confirmed that she plans to use the hubs **starting in August.** 

We need to discuss and decide on a policy for handling instances where the deployed hubs are not actively used during a semester. We are spending on monthly filestore and node pools for this hub which could exceed thousands of dollars by July 23. 

We should either a) Decommission unused hubs and create new ones based on instructor request or b) Either delete their filestore instances or move them to shared filestores, delete their node pools or add them to common pools, and archive user files stored in their home directories.

I will use this GitHub issue to track all the hubs that are not used during SP 23.

Hubs | Hub Status | Confirmed by | Additional Notes | Decision Made | Decision Communicated to Instructor
-- | -- | -- | -- | -- | --
Data 101 Hub | Not used | Lakshya Jain (FA 22 instructor for Data 101) and Lisa Yan (FA 23 instructor for Data 101) | She will use the hub starting August | Students are given a week's time to download their data | Instructors gave a thumbs up for deleting student data  
Astro Hub | Not used |  Josh Bloom (FA 22 instructor for Astro) | He will definitely use it for FA 23 and may use it during Summer 23 | Delete student data and explore folding Astro hub into main Datahub |Gave a thumbs up for deleting student data and requested a plan of action for handling package conflicts
CEE Hub | Not used|  Nicholas Sitar (FA 22 instructor for Civ Eng 170) | He will definitely use it for FA 23 and is on sabbatical during SP 23 | Delete student data | Instructor gave a thumbs up and informed students to back up.

# Tasks to complete

- [x] Decide policy on unused hubs
- [x] @balajialg to do outreach to instructors using Astro and CEE hub and update this list
- [x] Decommission Astro Hub
- [x] Decommission CEE Hub
- [x] Decommission Data 101 Hub

**Comment by balajialg** [comment]
- [x] Figure out UI for folks accessing these hubs?
- [x] Make a decision: Delete hubs? what happens to user files?

**Comment by shaneknapp** [comment]
filestore:  we can create backups, delete the instance, and create a new instance from the backup

backups are $.08/G/month

https://cloud.google.com/filestore/pricing

**Comment by ryanlovett** [comment]
Discussion notes...

Non-filestore steps to decommission a hub:
- set node pool size to 0
- set autoscaler to 0
- keep deployment assets in github
- disable deployment in CI

Filestore:
These courses cost about $700 a month in filestore.
- should we delete filestore
- should we snapshot filestore
- what if students need materials between active terms?

After course is over:
Method 0:
1. Announce that hub won't be available by a certain date.
2. Archive user data and delete filestore after that date.
3. Decommission hub.

Method 1:
1. For all non-instructors, archive users.
2. All data gets deleted, replaced with where-are-my-files.
5. That gets snapshotted. This is much smaller.
6. We'd still need the hub to exist in order for users to see where-are-my-files.

Method 2:
1. For all non-instructors, archive users.
2. All data gets deleted.
3. There is a where-are-my-files service. This wouldn't need a hub.

All backups for all filestore is 8 cents per gig, $22/day

**Comment by balajialg** [comment]
Meeting Notes - https://docs.google.com/document/d/1mUg6rxSdhYtZAERAiYVSUmu-iRKh5xFywaTAypUdgYE/edit?usp=sharing

**Comment by balajialg** [comment]
**Next Steps from the follow up meeting (03/30)**

- [ ] Data 101 hub: Outreach to the instructor one last time before making the final decision to delete student files
- [ ] Astro hub should get renamed with the course name to be clear about the purpose of its usage

**Comment by shaneknapp** [comment]
**steps to spin down a hub:**

- create filestore backup
- unmount filestore from nfsserver
- comment hub build steps out in circleci
- comment hub entries out in `datahub/node-placeholder`
- delete k8s namespace
- delete node pool
- delete filestore
- delete pv

**Comment by shaneknapp** [comment]
> * [x]  Figure out UI for folks accessing these hubs?
> * [x]  Make a decision: Delete hubs? what happens to user files?

404, user files are backed up in filestore

**Comment by balajialg** [comment]
Data 101 instructor Lakshya Jain gave a heads up for deleting files. Awaiting Lisa Yan's (who will be the new instructor for Data 101 next semester) confirmation for deleting Data 101 files!

Edit: Lisa Yan gave her heads up @shaneknapp

**Comment by shaneknapp** [comment]
this is also now done for data101

**Comment by balajialg** [comment]
Closing this issue as it got done. Thanks all for your awesome work here.
