### ISSUE TITLE
Schedule "Maintenance Window" during Spring Break 

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4365]
# Summary

Spring recess happens between March 27th - 31st, 2023 (Ref - https://registrar.berkeley.edu/wp-content/uploads/UCB_AcademicCalendar_2022-23.pdf). We need to choose the date for the next maintenance window and communicate that to all instructors who are currently using Datahub through the datahub-announce email list.

# Activities Scoped
- [x] Upgrade JupyterHub to the latest [4xx version](https://github.com/jupyterhub/jupyterhub/tags) (#4237)
- [x] Delete data from Astro, CEE and (if instructor permits) Data 101 hub (#4313) 
- [ ] Data 100 SQLite issue (#4222) [Descoped because of the lack of bandwidth]
- [ ] Enabling RTC in DLab (#4371) [Descoped because of the lack of bandwidth]
- [x] Creating groups in Jupyterhubs based on Canvas groups (#4379)

# Tasks to be Performed

- [x] Decide the dates for Maintenance Window (MW)
- [x] Outreach to instructors to communicate the dates for MW and identify if there are any course deadlines/assignments scheduled during the Spring break
- [x] Execute the window

Anything else I missed?

**Comment by shaneknapp** [comment]
just heard back from @yuvipanda and for us to deploy my fixes to the spawn timer metric, we'll need to deploy a beta 4 release:
https://github.com/jupyterhub/jupyterhub/issues/4351#issuecomment-1479306698
https://github.com/jupyterhub/jupyterhub/tags

**Comment by balajialg** [comment]
Thanks @shaneknapp! That's helpful info

Are there any activities scheduled for MW that I missed in this list @shaneknapp @ryanlovett @felder?

**Comment by ryanlovett** [comment]
There's also #4379. The PR is ready to go.

**Comment by balajialg** [comment]
Thanks @ryanlovett! Included that in the list.

**Comment by balajialg** [comment]
MW is between 27th - 30th!

**Comment by balajialg** [comment]
Closing this issue as Maintenance Window is done!
