### ISSUE TITLE
Tools to manage support process!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4366]
# Summary

Currently, GitHub is used for managing cards and supporting data retrieval requests from a support and project management standpoint. However, we are running into the following issues with Github for the above tasks

- **Access Control:** Anybody who is added to the GitHub repository to manage cards has merge access to the code base which is not an ideal scenario. We tried to get Sara (student worker at LET) Github access to handle data retrieval requests and move cards in the project board. We realized after a detailed exploration that she will also get PR merge access to the code base if we give her access to handle cards. As a result, even when she was invested in the effort we could not onboard her to support the data retrieval tasks.

- **Github Account:** Users requesting their files using Github share their email ids which can lead to FERPA compliance issues in the future

- **Project Management:** Performing project management tasks using Github is challenging in its own way It is hard to collect metrics in an automated way around a) tasks pending/completed during the month, b) time spent in total for each one of these tasks etc. This makes it hard to estimate the total dev hours spent in total against the available technical bandwidth.

One of the proposed solutions that came as a result of conversation with Richard is the suggestion to explore JIRA for project management activities and Service Now for data retrieval requests. I am currently exploring how these tools can integrate with our support and project management workflow.  

# Important information

- Rationale for looking at alternative pathways - https://docs.google.com/presentation/d/1khqGBhJVBVSbqhwdcDRtLZXhPMPulXNEZkaj2YWgm58/edit?usp=sharing

# Tasks to complete

- [x] Request access for JIRA and ServiceNow accounts
- [x] Create Datahub accounts in JIRA and ServiceNow
- [ ] Get all relevant folks added to JIRA and ServiceNow
- [x] Feed data from our existing Github issues and [product priorities spreadsheet](https://docs.google.com/spreadsheets/d/1w5rqaEmhol7KA1dcP9ZYIDT_CBsYGhtXBvEgiy33Swo/edit?usp=sharing) into JIRA
- [x] Run "Monthly Sprint Planning" meetings using JIRA
- [ ] Figure out tweaks to use ServiceNow for data retrieval requests
- [ ] Modify Where_are_my_files.txt to update the URL if ServiceNow is working great
