### ISSUE TITLE
Create test hub deployment for D-Lab!

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4375]
# Summary

@aculich is interested in the idea of [blue-green deployment ](https://www.redhat.com/en/topics/devops/what-is-blue-green-deployment) for D-Lab. He intends to use the D-Lab test hub for testing bleeding edge changes (by customizing images regularly) and the standard hub for running workshops. You can read more about his requirements [here](https://github.com/berkeley-dsep-infra/datahub/pull/4371#issuecomment-1468992678).

Are there ways to solve this requirement without creating new hubs? If not, can we create a new hub with URL dlab-testing.datahub.berkeley.edu which has its own staging and prod with admin rights for @aculich and their team so that they can customize their image as per their interests. We can have the node pools and filestores shared with the D-Lab hub inorder to optimize for cloud costs (Thanks @ryanlovett for the suggestion).

# User Stories

- As a `D-Lab Hub admin` I want to `test bleeding edge changes in a new hub` so that `the existing D-Lab deployment remains the stable hub which is not affected`.

# Acceptance Criteria

- As a D-Lab admin, I can test bleeding edge changes in a test hub dedicated to D-Lab admins.

# Important information

Most of the github repos that D-Lab uses come from one place: https://github.com/dlab-berkeley/
Which are the github repos that the [upcoming workshop list](https://dlab.berkeley.edu/training/upcoming-workshops) points to.

# Tasks to complete

- [ ] Evaluate whether there is a non hub approach to solve this requirement
- [ ] If not, Create a new hub
- [ ] Provide enough privileges for Aaron and team to customize the image
