### ISSUE TITLE
Isolate Data 102 Image from the Main Datahub Image

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4422]
# Summary

Like #4420 Data 102 instructors ran into a similar problem with Statsmodel and requested a package upgrade in the main hub image. In addition, they requested to isolate the Data 102 image from the Datahub image so that they can make such upgrades whenever necessary. 

# User Stories

- As a `Data 102 instructor` I want to `make changes to Data 102 image` so that `I don't worry about breaking other course workflow`.

# Acceptance criteria

- Data 102 instructors can make changes to their Data 102 hub image which is isolated from the main Datahub image

# Important information

Instructor request 

_Looking at the berkeley-dsep-infra repo, it looks like data102 doesn't have a custom image (i.e., there's no deployments/data102/image analogous to deployments/data100/image). What's the bare minimum necessary to fill that in so that we can have a custom deployments/data102/image/environment.yml file with statsmodels==0.13.5?_

# Tasks to complete

- [ ] Create Data 102 specific image
- [ ]  Reach out to the instructor to verify the urgency of this request (Now or during the maintenance window?)
- [ ] Verify whether Data 102 is taught during summer

**Comment by balajialg** [comment]
- [ ] Reach out to the instructor to verify the urgency of this request (Now or during the maintenance window?)
- [ ] Verify whether Data 102 is taught during summer

**Comment by balajialg** [comment]
Closing this issue as it got done
