### ISSUE TITLE
Configure Highschool Hub for Big Data club workshop

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4862]
# Summary

[Big Data at Berkeley](https://bd.berkeley.edu/) is a Data Science consulting organization run by students. They are conducting a 6-week workshop starting in early October to teach Data 8 style curriculum to high school students. They used Deepnote and Google Colab earlier but felt that it didn't fit their instructional workflow well as they were slow and non-dynamic respectively. So, they are exploring the idea of using Datahub for the current iteration of the program. 

120 students from school districts in Richmond, Dublin, Berkeley High, and Oakland will participate in the class happening on Saturdays from 9 AM - 3 PM. High School hub needs to to allow students with email ids from different school districts to login to the hub. In addition, there maybe scenarios where students might use their personal email id. We need to figure out the best way to allow such students to access High school hub

# Acceptance criteria

- All high school students from different school districts can access Jupyter Notebooks in High School hub.

# Important information

# Tasks to complete

- [x] Provide admin access for Melvin in High School Hub
- [ ] Melvin will try adding all student email ids through their admin privilege
- [ ] If that doesn't work, Allow domains from different school districts

**Comment by balajialg** [comment]
Depending on the types of email ids that will be reported by Melvin, we can either stick to the current approach of allowing Gmail logins using GoogleOAuthenticator vs shifting to [CILlogonauthenticator](https://github.com/2i2c-org/infrastructure/blob/a3a32035aa179080a7c983fe11d43632b648c7cd/config/clusters/callysto/common.values.yaml#L66) which provides federated identity management

**Comment by balajialg** [comment]
@smelvino doesn't have admin access currently despite #4864! Any idea why this might be the case?

The other domains that need to get added to the high school config are,

@ausdk12.org
@amethodschools.org
@wccschools.org
@madison.k12.wi.us
@student.tdsb.on.ca
@sfhs.com

**Comment by ryanlovett** [comment]
I cut all entries from config common and appended to those in secrets prod and that worked. Previously, I wonder if the secrets prod value was taking precedence, rather than being combined with config common. This should be investigated. @shaneknapp also previously was not an admin either, even though he was present in config common.

**Comment by balajialg** [comment]
Thanks a lot @ryanlovett! This is great. Can you either open a Github issue or a JIRA card for tracking this issue separately?

@smelvino Can you try logging in and check if you have the admin access? Also - we enabled authentication for the students from the above mentioned domains. Can you confirm whether the students are able to access the high school hub?

**Comment by balajialg** [comment]
Hi, @smelvino - Did you end up using the High School hub for your workshop? Just wanted to know this info for our reporting purposes

**Comment by balajialg** [comment]
Closing this issue since the request was served.
